### ISSUE TITLE
BasicNetwork.performRequest: Unexpected response code 404 

### ISSUE THREAD

**Issue by NicolNonga** [usekamba/teste-dev-alpha#7]
API esta a me returnar null , tentei outras APis e  retorna json , ja APi do Kambas me retorna null

**Comment by amarildolucas** [comment]
Olá @NicolNonga, quando abrir uma `issue com algum bug ou dificuldade por favor descreve tecnicamente o problema com detalhes.

Quanto a API ela está funcional no mesmo `TOKEN` enviado. 

Eu ia recomendar analisar a forma que está fazendo a chamada, de preferência o cabeçalho em `Authorization`.

`BasicNetwork.performRequest: Unexpected response code 404` me parece um erro local em seu código na linguagem que tenha escolhido.

Pode usar o Postman ou Curl se desejar confirmar a funcionalidade independente de linguagem.

Tente passar o Authorization da forma certa: `Authorization: Token SEU_TOKEN_AQUI`. É crucial ter o formato certo.

**Comment by NicolNonga** [comment]
Obrigado pelo feedback

**Comment by NicolNonga** [comment]
API em uso= https://kamba-api-staging.herokuapp.com/v1/activities

Usando Postman recebo essa mensagem no Header 
     Connection = "keep-alive";
    "Content-Length" = 0;
    "Content-Type" = "application/json; charset=utf-8";
   Date →Thu, 20 Sep 2018 20:40:28 GMT
    Server = Cowboy;
    Via = "1.1 vegur";
X-Request-Id →f6b74df6-1940-4909-97cd-5dd949f99c7e
    "X-Runtime" = "0.002844";
} }
Body: Optional({"status":"404","error":"Not Found"})

**Comment by NicolNonga** [comment]
Até agora sem feedback ja tentei com Postman e sem resultado,

**Comment by AlexJuca** [comment]
@NicolNonga tenta usar o seguinte endpoint -> 
https://kamba-api-staging.herokuapp.com/v1/users/activities

**Comment by NicolNonga** [comment]
@AlexJuca obrigado  agora sim, esta  me retornar

**Comment by amarildolucas** [comment]
Sendo que o problema foi corrigido estou fechando a issue.
